### ISSUE TITLE
New Shader (GlItch)

### ISSUE THREAD

**Issue by Rauf-ID** [crashinvaders/gdx-vfx#12]
hello. ur code is really awesome. I'm wondering if you could add a glitch effect to the shaders?

**Comment by metaphore** [comment]
Thanks for the input. A glitch effect is not the one you usually find out of the box and there are so many different ones. If you have an idea for the specific implementation or a good shader code reference for it, I'm happy to adapt it for the library, otherwise sorry, I cannot invest time in making it up from scratch.

**Comment by metaphore** [comment]
I'll close it due to inactivity. Happy to reopen if there's any input on the topic.
