### ISSUE TITLE
"Noise" missing

### ISSUE THREAD

**Issue by SteveSmith16384** [crashinvaders/gdx-vfx#13]
Hi, there is an effect in your demo called Noise, but doesn't seem to be available in the source.  Does it come under a different name?

**Comment by metaphore** [comment]
Hi there,
The noise effect [was removed](https://github.com/crashinvaders/gdx-vfx/commit/9ce2c93a978cf47e11d04e71b7a34a63724c14e2#diff-012073118c9355bf301cf053baae75f2) due to duplication with [`FilmGrainEffect`](https://github.com/crashinvaders/gdx-vfx/blob/master/gdx-vfx/effects/src/com/crashinvaders/vfx/effects/FilmGrainEffect.java), which can be configured to achieve pretty much the same result.

**Comment by SteveSmith16384** [comment]
I see.  Thanks, it's a great library.
